export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_LOADING = 'CREATE_EVENT_LOADING';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';

export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_EVENT_LOADING = 'UPDATE_EVENT_LOADING';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_ERROR = 'UPDATE_EVENT_ERROR';

export const FETCH_UPDATE_PARTICIPANTS = 'FETCH_UPDATE_PARTICIPANTS';
export const FETCH_UPDATE_PARTICIPANTS_SUCCESS = 'FETCH_UPDATE_PARTICIPANTS_SUCCESS';

export const READ_EVENTS = 'READ_EVENTS';
export const READ_EVENTS_LOADING = 'READ_EVENTS_LOADING';
export const READ_EVENTS_SUCCESS = 'READ_EVENTS_SUCCESS';
export const READ_EVENTS_ERROR = 'READ_EVENTS_ERROR';

export const FETCH_EVENT_DATA = 'FETCH_EVENT_DATA';
export const FETCH_EVENT_DATA_LOADING = 'FETCH_EVENT_DATA_LOADING';
export const FETCH_EVENT_DATA_SUCCESS = 'FETCH_EVENT_DATA_SUCCESS';
export const FETCH_EVENT_DATA_ERROR = 'FETCH_EVENT_DATA_ERROR';

export const CREATE_PURCHASE = 'CREATE_PURCHASE';

export const CHANGE_CURRENT_EVENT = 'CHANGE_CURRENT_EVENT';

export const CREATE_EVENT_ACTION = 'CREATE_EVENT_ACTION';

export const GET_LOCAL_EVENTS = 'GET_LOCAL_EVENTS';
export const SET_LOCAL_EVENTS = 'SET_LOCAL_EVENTS';

export const CHANGE_PURCHASE = 'CHANGE_PURCHASE';
export const LOAD_EVENT_DATA = 'LOAD_EVENT_DATA';

export const REPAY_DEBT = 'REPAY_DEBT';
export const REPAY_DEBT_SUCCESS = 'REPAY_DEBT_SUCCESS';

export const FETCH_PURCHASE_DELETE = 'FETCH_PURCHASE_DELETE';
export const RELOGIN = 'RELOGIN';
