export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_LOADING = 'CREATE_EVENT_LOADING';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR';

export const READ_EVENTS = 'READ_EVENTS';
export const READ_EVENTS_LOADING = 'READ_EVENTS_LOADING';
export const READ_EVENTS_SUCCESS = 'READ_EVENTS_SUCCESS';

export const LOAD_EVENT_DATA = 'LOAD_EVENT_DATA';

export const CREATE_PURCHASE = 'CREATE_PURCHASE';
